In [5]:
import pandas as pd
import numpy as np
df=pd.read_csv('C:/Users/admin/Desktop/python repo/результаты А_B - cookie_cats 2.csv')
df.shape

(90189, 5)

**Просмотрим общие показатели по двум группам . Из двух групп мы долждны выбрать ту у которой будет больший retention на седьмой день и не сильно снизится показатель проведённого времени в игре и проверить в итоге нет ли статистически значимых различий**

In [6]:
df.describe()

userid  sum_gamerounds   retention_1   retention_7
count  9.018900e+04    90189.000000  90189.000000  90189.000000
mean   4.998412e+06       51.872457      0.445210      0.186065
std    2.883286e+06      195.050858      0.496992      0.389161
min    1.160000e+02        0.000000      0.000000      0.000000
25%    2.512230e+06        5.000000      0.000000      0.000000
50%    4.995815e+06       16.000000      0.000000      0.000000
75%    7.496452e+06       51.000000      1.000000      0.000000
max    9.999861e+06    49854.000000      1.000000      1.000000

In [7]:
df.head(10)

userid  version  sum_gamerounds  retention_1  retention_7
0     116  gate_30               3            0            0
1     337  gate_30              38            1            0
2     377  gate_40             165            1            0
3     483  gate_40               1            0            0
4     488  gate_40             179            1            1
5     540  gate_40             187            1            1
6    1066  gate_30               0            0            0
7    1444  gate_40               2            0            0
8    1574  gate_40             108            1            1
9    1587  gate_40             153            1            0

**Проверим кол-во уникальных ID в датафрейме**

In [8]:
unique_user_id = df['userid'].nunique()
unique_user_id

90189

**Разделим датафрейм по группам и посмотрим показатели по каждой из них , для первичных выводов**

In [9]:
group_30=df.query('version == "gate_30"')
group_30.describe()

userid  sum_gamerounds   retention_1   retention_7
count  4.470000e+04    44700.000000  44700.000000  44700.000000
mean   4.987564e+06       52.456264      0.448188      0.190201
std    2.881026e+06      256.716423      0.497314      0.392464
min    1.160000e+02        0.000000      0.000000      0.000000
25%    2.505469e+06        5.000000      0.000000      0.000000
50%    4.983631e+06       17.000000      0.000000      0.000000
75%    7.481497e+06       50.000000      1.000000      0.000000
max    9.999710e+06    49854.000000      1.000000      1.000000

**В первой группе показатель ретеншн 7 равен 0.1902 . т.е 19% пользователей остаётся в игре из первоначальной выборки,  а также среднее кол-во раундов равно 52.4**

In [10]:
group_40=df.query('version == "gate_40"')
group_40.describe()

userid  sum_gamerounds   retention_1   retention_7
count  4.548900e+04    45489.000000  45489.000000  45489.000000
mean   5.009073e+06       51.298776      0.442283      0.182000
std    2.885496e+06      103.294416      0.496663      0.385849
min    3.770000e+02        0.000000      0.000000      0.000000
25%    2.517171e+06        5.000000      0.000000      0.000000
50%    5.007329e+06       16.000000      0.000000      0.000000
75%    7.510762e+06       52.000000      1.000000      0.000000
max    9.999861e+06     2640.000000      1.000000      1.000000

**Во второй группе показатель ретеншн 7 равен 0.182 . т.е 18% пользователей остаётся в игре из первоначальной выборки,что на 1 процент меньше , чем в первой группе , а также среднее кол-во раундов равно 51.2**

In [11]:
group_30.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44700 entries, 0 to 90186
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   userid          44700 non-null  int64 
 1   version         44700 non-null  object
 2   sum_gamerounds  44700 non-null  int64 
 3   retention_1     44700 non-null  int64 
 4   retention_7     44700 non-null  int64 
dtypes: int64(4), object(1)
memory usage: 2.0+ MB


In [12]:
group_40.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45489 entries, 2 to 90188
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   userid          45489 non-null  int64 
 1   version         45489 non-null  object
 2   sum_gamerounds  45489 non-null  int64 
 3   retention_1     45489 non-null  int64 
 4   retention_7     45489 non-null  int64 
dtypes: int64(4), object(1)
memory usage: 2.1+ MB


**Посчитаем какая доля юзеров осталась из первоночальной выборки в первой группе для использования Z -критерия в определении статзначимости результатов. На данный момент мы видим , что в контрольной группе показатели лучше , чем в тестовой и мы будем узнавать действительно ли это так** 

In [13]:
sum_30=44700
conv_30=44700*0.1902
conv_30

8501.94

In [14]:
sum_40=45489
conv_40=45489*0.182
conv_40

8278.998

In [15]:
import statsmodels.api as sm
import statsmodels.api as sm
z_stat, p_value = sm.stats.proportions_ztest([conv_30,conv_40], [sum_30, sum_40])
z_stat, p_value

(3.163862484170172, 0.0015569033975568595)

**Исходя из критерия видим , что статистически значимые различия в группах есть и результаты в тестовой группе не случайны** 

Посчитаем также как дополнительную метрику для вывода , общее кол-во раундов по контрольной группе  и оно равно 2344795 

In [16]:
sum_game_30= group_30['sum_gamerounds'].sum()

sum_game_30

2344795

И во тестовой группе , оно равно 2333530 . Что меньше чем в контрольной группе

In [17]:
sum_game_40= group_30['sum_gamerounds'].sum()

sum_game_30

2344795

**Так же можно расчитать значение мощность тетса для того , чтобы понимать хватило ли нам данных выборки для того , чтобы делать выводы по группам**

In [18]:
gr_30_mean = group_30.retention_7.values.mean()
gr_40_mean = group_40.retention_7.values.mean()
gr_30_std = group_30.retention_7.values.std()
gr_40_std = group_40.retention_7.values.std()
print(len(group_30.retention_7.values), len(group_40.retention_7.values))
#print(C_std,T_std)
gr_30_mean,gr_40_mean,gr_30_std,gr_40_std

44700 45489


(0.19020134228187918,
 0.18200004396667327,
 0.3924599236559711,
 0.3858445645111543)

In [19]:
n =  (len(group_30.retention_7.values)+len(group_40.retention_7.values))/2
S = np.sqrt((gr_30_std**2 + gr_40_std **2)/ 2)
ef =float((gr_30_mean-gr_40_mean)/ S) 
ef

0.021074019755891234

In [20]:
# parameters for power analysis
from statsmodels.stats.power import TTestIndPower
alpha = 0.05

# perform power analysis
analysis = TTestIndPower()
result = analysis.solve_power(ef, power=None,
nobs1=n, ratio=1.0, alpha=alpha)

result

0.8857870130972878

In [21]:
**Можность теста 88% говорит о том , что нам достаточно данных , чтобы утвержадть о том , что результаты ста **

SyntaxError: invalid syntax (Temp/ipykernel_15084/2466238112.py, line 1)

**Можно сделать вывод , что результаты в контрольной  группе лучше , чем результаты в тестовой и это является статистически значимым результатом , то есть не случайны.
Менеджеру компании не рекомендуется выкатывать обновления по игре , так как ключевые показатели снизились** 